name: Test
on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
          
      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
          
      - name: Install frontend dependencies
        run: pnpm install
        
      - name: Check frontend
        run: pnpm run check
        
      - name: Build frontend
        run: pnpm run build
        
      # Skip full Tauri build on PRs - just check frontend builds
      # - name: Build Tauri app (test build)
      #   run: pnpm run tauri build